### ISSUE TITLE
Limit Company Names to AlphaNumeric

### ISSUE THREAD

**Issue by Tsarcasm** [schlatt-co/stonks#12]
A company called GlassAss.com left chests not accessible by their owner.
This may be a special character name or a sign name truncation issue. I have a hunch that the period character didnt fit the chestshop sign line 1 regex.

I expect the best fix would be to prevent special characters in the name

**Comment by Tsarcasm** [comment]
This also happens with the ' character

**Comment by Tsarcasm** [comment]
Causes an SQL error with Ormlite

**Comment by JRoy** [comment]
This is why you need to convert to using prepared statements via `java.sql` package

**Comment by JRoy** [comment]
Should use Apache Commons's `StringUtils#isAlphanumericSpace` to verify company names

**Comment by Tsarcasm** [comment]
Solved this issue in #17 (e7ad0e801d9badb74816b76c6d360c8a19797b18)
