### ISSUE TITLE
Holding account for company balance

### ISSUE THREAD

**Issue by Krammittt** [schlatt-co/stonks#7]
When someone pays a holding account, right now it can only go to actual people, it'd be nice if you could make it so a cut of it would go to the company balance, that way if the company has a job they need to pay someone for, they can take it out of the company balance. Right now, the only way for money to go in to the entire company balance is if someone pays it directly

**Comment by Tsarcasm** [comment]
This is a good idea, some way of making a holding owned by a company. It sounds difficult on first glance because holdings are specific to a player, and checks would be required all over the codebase that requires holdings.
Holdings store players by UUID though so maybe it could be done.

**Comment by Tsarcasm** [comment]
On reflection, this is not possible with the current system, and while it would be nice it adds a level of complexity most users would not need this feature.
I've closed it for now, but I may reopen in the future if we do consider this
